[gcloud]
disabled = true

[custom.git_user]
command = """
email=$(git config user.email 2>/dev/null)
if [ -n "$email" ]; then
    echo "ðŸ¢ $email"
else
    echo "ðŸ¢ No email"
fi
"""
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
style = "bold yellow"
format = "[$output]($style) "
